-- Your SQL goes here
CREATE TABLE quests (
    id INTEGER PRIMARY KEY NOT NULL,
    cmd_name VARCHAR NOT NULL,
    pattern VARCHAR NOT NULL,
    query VARCHAR NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
